pub mod types;

mod calendar_events;
mod calendar_holidays;
pub(crate) mod catalog;
mod client_followup;
pub(crate) mod clients;
mod crm_opportunities;
mod recovery_actions;
mod discount_presets;
mod document_discount;
mod files;
mod fonts;
mod import_plugins;
mod invoices;
mod manual_revenue;
mod projects;
mod purchase_orders;
pub(crate) mod quotes;
mod snippets;
mod stock;
pub(crate) mod tax_rates;
mod workspaces;

pub use calendar_events::*;
pub use calendar_holidays::*;
pub use catalog::*;
pub use client_followup::*;
pub use clients::*;
pub use crm_opportunities::*;
pub use discount_presets::*;
pub use files::*;
pub use fonts::*;
pub use import_plugins::*;
pub use invoices::*;
pub use manual_revenue::*;
pub use projects::*;
pub use purchase_orders::*;
pub use quotes::*;
pub use recovery_actions::*;
pub use snippets::*;
pub use stock::*;
pub use tax_rates::*;
pub use workspaces::*;
