import { StyleSheet } from "@react-pdf/renderer";
import type { PdfTemplateVariantId } from "@/lib/pdfTemplateVariants";

/** Couleurs et espacements par variante (react-pdf : pas de CSS classique). `ff` = famille PDF standard (Helvetica, Times-Roman, Courier). */

function buildPdfVariantSheets(ff: string) {
  const classic = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: ff },
  stripeBanner: {},
  stripeBannerText: {},
  sidebar: {},
  sidebarLabel: {},
  sidebarText: {},
  mainColumn: {},
  /** Espace réservé ; le classique n’affiche pas de barre décorative avant le tableau. */
  preTableAccent: { height: 0, marginTop: 0, marginBottom: 0 },
  title: { fontSize: 18, marginBottom: 4, color: "#000000" },
  subtitle: { fontSize: 10, color: "#444", marginBottom: 12 },
  docTitle: { fontSize: 14, fontFamily: ff, marginBottom: 8, color: "#000000" },
  quoteMetaGrid: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 10,
    gap: 16,
  },
  quoteMetaCol: { flex: 1 },
  metaColHeading: { fontSize: 10, color: "#666", marginBottom: 3 },
  metaDateRow: { flexDirection: "row", marginBottom: 4, gap: 12 },
  row: { flexDirection: "row", marginBottom: 4 },
  label: { width: 100, color: "#666" },
  tableHeader: {
    flexDirection: "row",
    borderTopWidth: 2,
    borderTopColor: "#000000",
    borderBottomWidth: 2,
    borderBottomColor: "#000000",
    paddingTop: 6,
    paddingBottom: 6,
    marginTop: 12,
  },
  tableHeaderText: {
    fontFamily: ff,
    fontSize: 10,
    color: "#000000",
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 4,
    borderBottomWidth: 0.5,
    borderBottomColor: "#999999",
  },
  colDesc: { flex: 3 },
  colNum: { flex: 1, textAlign: "right" },
  totals: {
    marginTop: 14,
    alignSelf: "flex-end",
    width: 200,
    borderTopWidth: 2,
    borderTopColor: "#000000",
    paddingTop: 8,
  },
  totalLine: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 2,
  },
  blockTitle: { fontSize: 11, marginTop: 12, marginBottom: 4 },
  blockText: { fontSize: 9, color: "#333", lineHeight: 1.4 },
  logo: { width: 80, height: 40, objectFit: "contain", marginBottom: 8 },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#666",
  },
});

const modern = StyleSheet.create({
  page: { padding: 48, fontSize: 10, fontFamily: ff, color: "#1a1a1a" },
  stripeBanner: {},
  stripeBannerText: {},
  sidebar: {},
  sidebarLabel: {},
  sidebarText: {},
  mainColumn: {},
  preTableAccent: {
    height: 5,
    width: 96,
    backgroundColor: "#1e293b",
    marginTop: 8,
    marginBottom: 14,
  },
  title: { fontSize: 20, marginBottom: 6, fontFamily: ff, color: "#0f172a" },
  subtitle: { fontSize: 10, color: "#64748b", marginBottom: 16 },
  docTitle: { fontSize: 13, fontFamily: ff, marginBottom: 10, color: "#0f172a" },
  quoteMetaGrid: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
    gap: 20,
  },
  quoteMetaCol: { flex: 1 },
  metaColHeading: { fontSize: 10, color: "#64748b", marginBottom: 4 },
  metaDateRow: { flexDirection: "row", marginBottom: 5, gap: 16 },
  row: { flexDirection: "row", marginBottom: 5 },
  label: { width: 100, color: "#64748b" },
  tableHeader: {
    flexDirection: "row",
    borderLeftWidth: 6,
    borderLeftColor: "#334155",
    borderTopWidth: 1,
    borderTopColor: "#cbd5e1",
    borderBottomWidth: 1,
    borderBottomColor: "#cbd5e1",
    borderRightWidth: 1,
    borderRightColor: "#e2e8f0",
    backgroundColor: "#f1f5f9",
    paddingVertical: 10,
    paddingHorizontal: 10,
    marginTop: 4,
  },
  tableHeaderText: {
    fontFamily: ff,
    fontSize: 8,
    color: "#1e293b",
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 7,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  colDesc: { flex: 3 },
  colNum: { flex: 1, textAlign: "right" },
  totals: {
    marginTop: 18,
    alignSelf: "flex-end",
    width: 220,
    padding: 12,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderLeftWidth: 6,
    borderLeftColor: "#475569",
    backgroundColor: "#f8fafc",
  },
  totalLine: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 3,
    fontSize: 10,
  },
  blockTitle: { fontSize: 10, fontFamily: ff, marginTop: 14, marginBottom: 4, color: "#0f172a" },
  blockText: { fontSize: 9, color: "#475569", lineHeight: 1.45 },
  logo: { width: 88, height: 44, objectFit: "contain", marginBottom: 10 },
  footer: {
    position: "absolute",
    bottom: 28,
    left: 48,
    right: 48,
    fontSize: 8,
    color: "#94a3b8",
  },
});

const stripe = StyleSheet.create({
  page: { padding: 40, paddingTop: 52, fontSize: 10, fontFamily: ff },
  preTableAccent: { height: 0, marginTop: 0, marginBottom: 0 },
  stripeBanner: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 38,
    backgroundColor: "#1d4ed8",
    justifyContent: "center",
    paddingHorizontal: 40,
  },
  stripeBannerText: { color: "#ffffff", fontSize: 11, fontFamily: ff },
  sidebar: {},
  sidebarLabel: {},
  sidebarText: {},
  mainColumn: {},
  title: { fontSize: 17, marginBottom: 4, color: "#0f172a" },
  subtitle: { fontSize: 10, color: "#475569", marginBottom: 10 },
  docTitle: { fontSize: 12, fontFamily: ff, marginBottom: 8, color: "#1e40af" },
  quoteMetaGrid: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 10,
    gap: 16,
  },
  quoteMetaCol: { flex: 1 },
  metaColHeading: { fontSize: 10, color: "#64748b", marginBottom: 3 },
  metaDateRow: { flexDirection: "row", marginBottom: 3, gap: 12 },
  row: { flexDirection: "row", marginBottom: 3 },
  label: { width: 95, color: "#64748b" },
  tableHeader: {
    flexDirection: "row",
    borderBottomWidth: 2,
    borderBottomColor: "#1d4ed8",
    paddingBottom: 5,
    marginTop: 12,
  },
  tableHeaderText: {
    fontFamily: ff,
    fontSize: 9,
    color: "#0f172a",
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 4,
    borderBottomWidth: 0.5,
    borderBottomColor: "#cbd5e1",
  },
  colDesc: { flex: 3 },
  colNum: { flex: 1, textAlign: "right" },
  totals: { marginTop: 12, alignSelf: "flex-end", width: 200, borderTopWidth: 1, borderTopColor: "#1d4ed8", paddingTop: 8 },
  totalLine: { flexDirection: "row", justifyContent: "space-between", marginBottom: 2 },
  blockTitle: { fontSize: 10, fontFamily: ff, marginTop: 12, marginBottom: 3, color: "#1e3a8a" },
  blockText: { fontSize: 9, color: "#334155", lineHeight: 1.4 },
  logo: { width: 76, height: 38, objectFit: "contain", marginBottom: 6 },
  footer: {
    position: "absolute",
    bottom: 28,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#64748b",
  },
});

const studio = StyleSheet.create({
  page: { padding: 36, fontSize: 10, fontFamily: ff },
  preTableAccent: { height: 0, marginTop: 0, marginBottom: 0 },
  stripeBanner: {},
  stripeBannerText: {},
  sidebar: {
    width: 92,
    backgroundColor: "#0f172a",
    padding: 10,
    minHeight: 120,
  },
  sidebarLabel: { fontSize: 7, color: "#94a3b8", marginBottom: 4 },
  sidebarText: { fontSize: 10, color: "#f8fafc", lineHeight: 1.35 },
  mainColumn: { flex: 1, paddingLeft: 14 },
  title: { fontSize: 16, marginBottom: 3, color: "#0f172a" },
  subtitle: { fontSize: 9, color: "#64748b", marginBottom: 8 },
  docTitle: { fontSize: 13, fontFamily: ff, marginBottom: 6, color: "#0f172a" },
  quoteMetaGrid: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 8,
    gap: 12,
  },
  quoteMetaCol: { flex: 1 },
  metaColHeading: { fontSize: 9, color: "#64748b", marginBottom: 3 },
  metaDateRow: { flexDirection: "row", marginBottom: 3, gap: 10 },
  row: { flexDirection: "row", marginBottom: 3 },
  label: { width: 90, color: "#64748b", fontSize: 9 },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#e2e8f0",
    paddingVertical: 6,
    paddingHorizontal: 5,
    marginTop: 10,
  },
  tableHeaderText: {
    fontFamily: ff,
    fontSize: 8,
    color: "#0f172a",
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 4,
    paddingHorizontal: 5,
    borderBottomWidth: 0.5,
    borderBottomColor: "#cbd5e1",
  },
  colDesc: { flex: 3 },
  colNum: { flex: 1, textAlign: "right", fontSize: 9 },
  totals: { marginTop: 10, alignSelf: "flex-end", width: 195 },
  totalLine: { flexDirection: "row", justifyContent: "space-between", marginBottom: 2, fontSize: 9 },
  blockTitle: { fontSize: 9, fontFamily: ff, marginTop: 10, marginBottom: 3 },
  blockText: { fontSize: 8, color: "#334155", lineHeight: 1.4 },
  logo: { width: 72, height: 36, objectFit: "contain", marginBottom: 6 },
  footer: {
    position: "absolute",
    bottom: 26,
    left: 36,
    right: 36,
    fontSize: 7,
    color: "#64748b",
  },
});

const compact = StyleSheet.create({
  page: { padding: 32, fontSize: 8.5, fontFamily: ff },
  preTableAccent: { height: 0, marginTop: 0, marginBottom: 0 },
  stripeBanner: {},
  stripeBannerText: {},
  sidebar: {},
  sidebarLabel: {},
  sidebarText: {},
  mainColumn: {},
  title: { fontSize: 14, marginBottom: 2, fontFamily: ff },
  subtitle: { fontSize: 8, color: "#555", marginBottom: 6 },
  docTitle: { fontSize: 11, fontFamily: ff, marginBottom: 5 },
  quoteMetaGrid: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 6,
    gap: 10,
  },
  quoteMetaCol: { flex: 1 },
  metaColHeading: { fontSize: 8, color: "#666", marginBottom: 2 },
  metaDateRow: { flexDirection: "row", marginBottom: 2, gap: 8 },
  row: { flexDirection: "row", marginBottom: 2 },
  label: { width: 78, color: "#666", fontSize: 8 },
  tableHeader: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#000",
    paddingBottom: 2,
    marginTop: 8,
  },
  tableHeaderText: {
    fontFamily: ff,
    fontSize: 8,
    color: "#000000",
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 2,
    borderBottomWidth: 0.5,
    borderBottomColor: "#bbb",
    fontSize: 8,
  },
  colDesc: { flex: 3 },
  colNum: { flex: 1, textAlign: "right" },
  totals: { marginTop: 8, alignSelf: "flex-end", width: 175 },
  totalLine: { flexDirection: "row", justifyContent: "space-between", marginBottom: 1, fontSize: 8 },
  blockTitle: { fontSize: 9, fontFamily: ff, marginTop: 8, marginBottom: 2 },
  blockText: { fontSize: 7.5, color: "#333", lineHeight: 1.35 },
  logo: { width: 64, height: 32, objectFit: "contain", marginBottom: 4 },
  footer: {
    position: "absolute",
    bottom: 22,
    left: 32,
    right: 32,
    fontSize: 7,
    color: "#666",
  },
});

  return {
    classic,
    modern,
    stripe,
    studio,
    compact,
  } as unknown as Record<PdfTemplateVariantId, typeof classic>;
}

export type PdfVariantStyles = ReturnType<
  typeof buildPdfVariantSheets
>[PdfTemplateVariantId];

export function stylesForPdfVariant(
  variant: PdfTemplateVariantId,
  bodyFontFamily: string,
): PdfVariantStyles {
  const sheets = buildPdfVariantSheets(bodyFontFamily);
  return sheets[variant] ?? sheets.classic;
}
